<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
    <RootNamespace>TarantoJ.FeatureManagement.Optimizely</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="microsoft.extensions.dependencyinjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" Version="10.9.0" />
    <PackageReference Include="Microsoft.FeatureManagement" Version="4.6.0" />
    <PackageReference Include="Optimizely.SDK" Version="4.4.0" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.32.0.713">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="4.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net10.0' and '$(TargetFramework)' != 'net11.0'">
    <PackageReference Include="system.linq.async" Version="7.0.1" />
  </ItemGroup>

</Project>
