# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build --no-restore src
    - name: JetBrains ReSharper Inspect Code
      uses: JetBrains/ReSharper-InspectCode@v0.3
      with:
        solution: ./src/TarantoJ.FeatureManagement.Optimizely.csproj
        tool-version: 2024.1.2
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
